### ISSUE TITLE
Program crashes when loads an invalid XML file

### ISSUE THREAD

**Issue by Delphi-Laie** [jaenicke/usermanager#2]
Dear Sebastian,

if a XML file is via "Extras -> Benutzer importieren" loaded and this file is invalid, then the program crashes.

The responsible function for that is "ImportXMLThread", although there is a try finally block inside.

Simple proposal for solution: a further try except block "around" the try finally block.

Thanks for attention and solution in progress!

Kindly regards,

Delphi-Laie

**Comment by jaenicke** [comment]
Thank you for your message. I corrected the issue.
