### ISSUE TITLE
Moin Moin, zwei Fragen

### ISSUE THREAD

**Issue by assarbad** [jaenicke/usermanager#6]
Hallo @jaenicke,

zwei kurze Fragen:

1. wurde schonmal angedacht das auf Englisch zu übersetzen? Sollte sich ja machen lassen und ich kann gern versuchen aus den hinteren Ecken meines Hirns noch Delphi-Restkenntnisse zu kratzen um mitzuhelfen. Erstens würde das deutlich das Publikum erweitern und zweitens -- oder hatte sich Luckie je gegen eine Übersetzung geäußert? -- würde es sein Vermächtnis ja eher vergrößern. Muttersprachler finden sich notfalls auch zum Korrekturlesen, aber ich bin auch flüssig auf Englisch unterwegs.
2. Da ich sehe -- lustigerweise hatte mir Luckie schon vor Jahren, lange bevor er es quelloffen stellte, die Quellen mal geschickt und ich hab nie reingeschaut -- daß es nonVCL ist, könnte das Teil doch sogar eventuell mit FreePascal bauen. Hat das mal jemand probiert? Die letzte Delphiversion die ich hatte war glaub ich XE oder XE2 und die habe ich noch nicht einmal richtig genutzt.

Gruß aus Frankfurt,

Oliver

**Comment by jaenicke** [comment]
Hallo Oliver,

ich habe die offenen Issues erst jetzt gesehen, weil ich hierdurch neue Benachrichtigungen bekommen habe.

1. Es spricht nichts gegen eine entsprechende Übersetzung, nein. Im Quelltext sind die Strings aktuell hardcoded verstreut. Das ließe sich sicherlich relativ einfach ändern, wird halt nur etwas Aufwand.

2. Darüber habe ich bisher nicht nachgedacht, aber da der Quelltext relativ alt ist und nur wenige Units von Delphi verwendet werden, könnte sich der Aufwand in Grenzen halten.
Ein Unterschied, der hier relevant sein könnte, ist z.B. das Pointerhandling. Das lässt sich natürlich leicht anpassen. Die Frage ist auch, ob alle Typen auch in Lazarus / FreePascal zur Verfügung stehen, sonst müsste man die dort noch deklarieren.

Leider sieht es bei mir zeitlich aktuell schlecht aus für die nächsten Wochen. Ich schaue es mir mal an.

Viele Grüße
Sebastian

**Comment by assarbad** [comment]
Zeitmangel ist wohl universell. Kein Ding. Ich wollte vor allem erstmal eruieren ob ggf. Interesse/Wille da ist. Ich guck mir bei Gelegenheit mal den Teil mit der Übersetzung näher an, vielleicht kommen mir dann schon Ideen wie man's angehen kann.

Und dabei kann man dann vielleicht ja schonmal schauen ob es überhaupt portabel sein könnte. Werde mir mal ein altes Delphi in eine Entwicklungs-VM kippen 😁 (falls ich die Lizenz nach den ganzen Eigentümerwechseln noch irgendwie aktiviert bekomme).

Beste Grüße,

Oliver
